all: 1 2 3

1:
	$(MAKE) -C 1-gpioExample

2:
	$(MAKE) -C 2-uartExample

3:
	$(MAKE) -C 3-timerExample

clean:
	$(MAKE) -C 1-gpioExample clean
	$(MAKE) -C 2-uartExample clean
	$(MAKE) -C 3-timerExample clean
